deploy:
  needs: build
  runs-on: ubuntu-latest

  steps:
  - name: Baixar artefatos do build
    uses: actions/download-artifact@v4
    with:
      name: build-frontend
      path: ./build

  - name: Criar o arquivo .pem e configurar permissões
    run: |
      echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > $HOME/private_key.pem
      chmod 400 $HOME/private_key.pem

  - name: Verificar chave privada (debug)
    run: |
      echo "Verificando chave privada..."
      ls -al $HOME/private_key.pem

  - name: Enviar arquivos para a EC2 via SCP
    uses: appleboy/scp-action@master
    with:
      host: ${{ secrets.EC2_PUBLIC_IP }}
      username: ubuntu
      key_path: $HOME/private_key.pem
      port: 22
      source: "./build/"
      target: "/home/ubuntu/sustentare-web/build/"
      rm: true

  - name: Configurar servidor na EC2
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.EC2_PUBLIC_IP }}
      username: ubuntu
      key_path: $HOME/private_key.pem
      port: 22
      script: |
        if ! command -v serve &> /dev/null; then
          sudo npm install -g serve
        fi

        cd /home/ubuntu/sustentare-web/build
        pm2 delete sustentare-web || true
        pm2 start npx --name sustentare-web -- serve -s . -l 3000
        pm2 save
